### ISSUE TITLE
Error when using the plugin

### ISSUE THREAD

**Issue by ahassen** [conundrumer/material-ui-mdi#2]
I followed the instruction on the readme to add an icon to my app and I get this error:

> Module not found: Error: Cannot resolve module 'material-ui/lib/svg-icon'

On further investigation I found that this like was causing the issue,

`var _materialUiLibSvgIcon = require('material-ui/lib/svg-icon');`

This import line is found on every icon's js file, and it's causing an error because it's unable to find `material-ui/lib/svg-icon`. I think `material ui`'s update removed this directory and `material-ui-mdi` hasn't updated accordingly. Will we be able to get an update to support material ui's restructuring? 

I'm using  `"material-ui": "^0.15.4"`

**Comment by conundrumer** [comment]
I'm actually thinking of deprecating this package for a more flexible alternative.

**Comment by conundrumer** [comment]
@ahassen check out https://github.com/conundrumer/mdi-svg
